package org.quasigroup.ibclient.client

object ServerVersion {
   val MIN_SERVER_VER_REAL_TIME_BARS = 34
   val MIN_SERVER_VER_SCALE_ORDERS = 35
   val MIN_SERVER_VER_SNAPSHOT_MKT_DATA = 35
   val MIN_SERVER_VER_SSHORT_COMBO_LEGS = 35
   val MIN_SERVER_VER_WHAT_IF_ORDERS = 36
   val MIN_SERVER_VER_CONTRACT_CONID = 37
   val MIN_SERVER_VER_PTA_ORDERS = 39
   val MIN_SERVER_VER_FUNDAMENTAL_DATA = 40
   val MIN_SERVER_VER_UNDER_COMP = 40
   val MIN_SERVER_VER_CONTRACT_DATA_CHAIN = 40
   val MIN_SERVER_VER_SCALE_ORDERS2 = 40
   val MIN_SERVER_VER_ALGO_ORDERS = 41
   val MIN_SERVER_VER_EXECUTION_DATA_CHAIN = 42
   val MIN_SERVER_VER_NOT_HELD = 44
   val MIN_SERVER_VER_SEC_ID_TYPE = 45
   val MIN_SERVER_VER_PLACE_ORDER_CONID = 46
   val MIN_SERVER_VER_REQ_MKT_DATA_CONID = 47
   val MIN_SERVER_VER_REQ_CALC_IMPLIED_VOLAT = 49
   val MIN_SERVER_VER_REQ_CALC_OPTION_PRICE = 50
   val MIN_SERVER_VER_CANCEL_CALC_IMPLIED_VOLAT = 50
   val MIN_SERVER_VER_CANCEL_CALC_OPTION_PRICE = 50
   val MIN_SERVER_VER_SSHORTX_OLD = 51
   val MIN_SERVER_VER_SSHORTX = 52
   val MIN_SERVER_VER_REQ_GLOBAL_CANCEL = 53
   val MIN_SERVER_VER_HEDGE_ORDERS = 54
   val MIN_SERVER_VER_REQ_MARKET_DATA_TYPE = 55
   val MIN_SERVER_VER_OPT_OUT_SMART_ROUTING = 56
   val MIN_SERVER_VER_SMART_COMBO_ROUTING_PARAMS = 57
   val MIN_SERVER_VER_DELTA_NEUTRAL_CONID = 58
   val MIN_SERVER_VER_SCALE_ORDERS3 = 60
   val MIN_SERVER_VER_ORDER_COMBO_LEGS_PRICE = 61
   val MIN_SERVER_VER_TRAILING_PERCENT = 62
   val MIN_SERVER_VER_DELTA_NEUTRAL_OPEN_CLOSE = 66
   val MIN_SERVER_VER_ACCT_SUMMARY = 67
   val MIN_SERVER_VER_TRADING_CLASS = 68
   val MIN_SERVER_VER_SCALE_TABLE = 69
   val MIN_SERVER_VER_LINKING = 70
   val MIN_SERVER_VER_ALGO_ID = 71
   val MIN_SERVER_VER_OPTIONAL_CAPABILITIES = 72
   val MIN_SERVER_VER_ORDER_SOLICITED = 73
   val MIN_SERVER_VER_LINKING_AUTH = 74
   val MIN_SERVER_VER_PRIMARYEXCH = 75
}
